/**
 * Catálogo de templates — fonte única de verdade.
 * O seed SQL (supabase/migrations/0002_seed_templates.sql) é gerado a partir daqui:
 *   pnpm seed:templates
 */
import type { z } from "zod";
import type { PlanId } from "@/lib/plans";
import {
  templateLayoutSchema,
  type TemplateLayout,
  type templateSampleSchema,
} from "@/lib/schemas/carousel.zod";

export type TemplateSample = z.infer<typeof templateSampleSchema>;

export type CatalogTemplate = {
  id: string;
  name: string;
  description: string;
  category: string;
  /** "pro" = coleção com layouts avançados (post, revista, checklist, número, vidro, neo brutal). */
  collection: "essenciais" | "pro";
  requiredPlan: PlanId;
  layout: TemplateLayout;
  sample: TemplateSample;
};

const t = (
  n: number,
  name: string,
  category: string,
  description: string,
  layout: z.input<typeof templateLayoutSchema>,
  sample: TemplateSample,
  requiredPlan: PlanId = "free",
  collection: CatalogTemplate["collection"] = "essenciais",
): CatalogTemplate => ({
  id: `7e3a0000-0000-4000-8000-${String(n).padStart(12, "0")}`,
  name,
  description,
  category,
  collection,
  requiredPlan,
  // Valida e completa os padrões (destaque, nome da marca…).
  layout: templateLayoutSchema.parse({ ...layout, sample, collection }),
  sample,
});

const pro = (
  n: number,
  name: string,
  category: string,
  description: string,
  layout: z.input<typeof templateLayoutSchema>,
  sample: TemplateSample,
  requiredPlan: PlanId = "free",
) => t(n, name, category, description, layout, sample, requiredPlan, "pro");

export const TEMPLATE_CATALOG: CatalogTemplate[] = [
  t(
    1,
    "Nutri Fresh",
    "Nutrição",
    "Verde vivo e leitura leve para dicas de alimentação.",
    {
      niche: "Nutrição",
      sequence: { first: "bold-hook", middle: ["numbered"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#14532d", secondary: "#f0fdf4", accent: "#84cc16", text: "#052e16", bg: "#f7fee7" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "dots",
      },
    },
    {
      hook: "Seu café da manhã está te deixando com fome",
      title: "Proteína logo cedo",
      body: "Ovos, iogurte natural ou queijo branco aumentam a saciedade e evitam o beliscão das 10h. Combine com uma fruta e uma fonte de fibra.",
      cta: "Salve para montar seu cardápio da semana",
      photo: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1080&h=1350",
    },
  ),
  t(
    2,
    "Treino Bruto",
    "Fitness",
    "Preto e amarelo de academia, tipografia pesada.",
    {
      niche: "Fitness",
      sequence: { first: "bold-hook", middle: ["split", "numbered"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#0a0a0a", secondary: "#fafafa", accent: "#facc15", text: "#fafafa", bg: "#171717" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "grid",
      },
    },
    {
      hook: "Você treina muito e evolui pouco?",
      title: "Sobrecarga progressiva",
      body: "Aumente carga, repetições ou volume a cada semana. Sem estímulo novo, o corpo não tem motivo para mudar.",
      cta: "Comente TREINO e receba a planilha",
    },
  ),
  t(
    3,
    "Grana Clara",
    "Finanças",
    "Azul profundo e laranja para educação financeira.",
    {
      niche: "Finanças",
      sequence: { first: "bold-hook", middle: ["numbered"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#1e1b4b", secondary: "#ffffff", accent: "#f97316", text: "#111111", bg: "#fafafa" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
      },
    },
    {
      hook: "5 erros que drenam seu salário todo mês",
      title: "Sem reserva de emergência",
      body: "Guarde de 6 a 12 meses de custos em liquidez diária antes de investir. Sem isso, qualquer imprevisto te obriga a vender na baixa.",
      cta: "Salve e comente INVESTIR",
    },
  ),
  t(
    4,
    "Growth Neon",
    "Marketing Digital",
    "Roxo elétrico com glow para conteúdo de marketing.",
    {
      niche: "Marketing Digital",
      sequence: { first: "bold-hook", middle: ["split", "minimal"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#2e1065", secondary: "#faf5ff", accent: "#d946ef", text: "#faf5ff", bg: "#0f0a1e" },
        fonts: { heading: "Space Grotesk", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "glow",
      },
    },
    {
      hook: "Seu conteúdo não vende por um motivo",
      title: "Falta uma oferta clara",
      body: "Todo post precisa levar a um próximo passo. Sem uma oferta explícita, o seguidor consome, curte e vai embora.",
      cta: "Envie OFERTA no direct",
    },
  ),
  t(
    5,
    "Toga Clássica",
    "Advocacia",
    "Serifada e sóbria para escritórios de advocacia.",
    {
      niche: "Advocacia",
      sequence: { first: "minimal", middle: ["minimal", "numbered"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#1c1917", secondary: "#fafaf9", accent: "#a16207", text: "#1c1917", bg: "#f5f5f4" },
        fonts: { heading: "Playfair Display", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "frame",
      },
    },
    {
      hook: "Demitido sem justa causa? Conheça seus direitos",
      title: "Aviso prévio proporcional",
      body: "Além dos 30 dias, você ganha 3 dias a mais por ano trabalhado, até o limite de 90 dias. Confira se isso entrou na sua rescisão.",
      cta: "Salve e compartilhe com quem precisa",
    },
    "business",
  ),
  t(
    6,
    "Chave Prime",
    "Imobiliário",
    "Azul petróleo e dourado para corretores e imobiliárias.",
    {
      niche: "Imobiliário",
      sequence: { first: "bold-hook", middle: ["editorial", "split"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#0c4a6e", secondary: "#f0f9ff", accent: "#eab308", text: "#0c1a24", bg: "#f8fafc" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
      },
    },
    {
      hook: "Comprar ou alugar em 2026? Faça essa conta",
      title: "Custo real da compra",
      body: "Some ITBI, escritura, registro e juros do financiamento. Compare com o aluguel mais o rendimento do dinheiro da entrada aplicado.",
      cta: "Chame no direct para uma simulação",
    },
    "business",
  ),
  t(
    7,
    "Mente Calma",
    "Psicologia",
    "Tons terrosos e acolhedores para saúde mental.",
    {
      niche: "Psicologia",
      sequence: { first: "minimal", middle: ["minimal"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#78350f", secondary: "#fffbeb", accent: "#d97706", text: "#292524", bg: "#fdf8f3" },
        fonts: { heading: "Playfair Display", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
      },
    },
    {
      hook: "Ansiedade não é frescura. É um alarme",
      title: "Nomeie o que sente",
      body: "Dizer em voz alta 'estou ansioso' reduz a ativação da amígdala. Nomear a emoção é o primeiro passo para regulá-la.",
      cta: "Salve para ler quando precisar",
    },
  ),
  t(
    8,
    "Sorriso Clean",
    "Odontologia",
    "Azul claro e branco, visual clínico e confiável.",
    {
      niche: "Odontologia",
      sequence: { first: "bold-hook", middle: ["numbered"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#0369a1", secondary: "#f0f9ff", accent: "#06b6d4", text: "#0f172a", bg: "#f8fafc" },
        fonts: { heading: "Inter", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "dots",
      },
    },
    {
      hook: "Escovar forte está destruindo seu esmalte",
      title: "Escova macia sempre",
      body: "Cerdas duras e força excessiva causam retração gengival e sensibilidade. O que limpa é a técnica, não a pressão.",
      cta: "Agende sua avaliação pelo direct",
    },
  ),
  t(
    9,
    "Glow Rosé",
    "Estética e Beleza",
    "Rosé elegante para skincare e estética.",
    {
      niche: "Estética e Beleza",
      sequence: { first: "bold-hook", middle: ["editorial", "minimal"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#831843", secondary: "#fdf2f8", accent: "#ec4899", text: "#3b0a24", bg: "#fff5f9" },
        fonts: { heading: "Playfair Display", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "glow",
      },
    },
    {
      hook: "O passo do skincare que você está pulando",
      title: "Protetor solar diário",
      body: "Nenhum ativo funciona se a pele está sendo agredida pelo sol. Reaplique a cada 3 horas, mesmo em dias nublados.",
      cta: "Comente PELE e receba a rotina",
      photo: "https://images.pexels.com/photos/3997993/pexels-photo-3997993.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1080&h=1350",
    },
  ),
  t(
    10,
    "Sala de Aula",
    "Educação",
    "Amarelo e azul, didático e amigável.",
    {
      niche: "Educação",
      sequence: { first: "bold-hook", middle: ["numbered", "split"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#1d4ed8", secondary: "#eff6ff", accent: "#f59e0b", text: "#0f172a", bg: "#fffdf5" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "grid",
      },
    },
    {
      hook: "Estude menos horas e aprenda mais",
      title: "Revisão espaçada",
      body: "Revise o conteúdo 1 dia, 3 dias e 7 dias depois da aula. Cada revisão no momento certo fortalece a memória de longo prazo.",
      cta: "Salve e mande para sua turma",
    },
  ),
  t(
    11,
    "Terminal",
    "Tecnologia",
    "Dark mode com verde terminal para devs e tech.",
    {
      niche: "Tecnologia",
      sequence: { first: "bold-hook", middle: ["split", "numbered"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#020617", secondary: "#e2e8f0", accent: "#22c55e", text: "#e2e8f0", bg: "#0b1120" },
        fonts: { heading: "Space Grotesk", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "grid",
      },
    },
    {
      hook: "Seu código lento tem um culpado comum",
      title: "Consultas N+1",
      body: "Buscar dados dentro de um loop gera uma query por item. Carregue tudo de uma vez com join ou busca em lote.",
      cta: "Siga para mais dicas de performance",
    },
  ),
  t(
    12,
    "Passarela",
    "Moda",
    "Preto, off-white e serifada editorial.",
    {
      niche: "Moda",
      sequence: { first: "editorial", middle: ["editorial", "minimal"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#171717", secondary: "#fafaf9", accent: "#b45309", text: "#171717", bg: "#f5f3ef" },
        fonts: { heading: "Playfair Display", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
      },
    },
    {
      hook: "Peças que fazem qualquer look parecer caro",
      title: "Blazer bem cortado",
      body: "Um blazer de alfaiataria em cor neutra transforma jeans e camiseta em produção. Invista no caimento dos ombros.",
      cta: "Salve para sua próxima compra",
    },
  ),
  t(
    13,
    "Sabor Caseiro",
    "Gastronomia",
    "Vermelho tomate e creme, cara de cozinha.",
    {
      niche: "Gastronomia",
      sequence: { first: "bold-hook", middle: ["numbered"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#991b1b", secondary: "#fff7ed", accent: "#ea580c", text: "#1c0a00", bg: "#fffaf0" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "dots",
      },
    },
    {
      hook: "O segredo do arroz soltinho de restaurante",
      title: "Lave até a água ficar clara",
      body: "Tirar o excesso de amido evita que os grãos grudem. Depois refogue no alho e óleo antes de colocar a água fervente.",
      cta: "Comente RECEITA e receba o passo a passo",
    },
  ),
  t(
    14,
    "Próximo Nível",
    "Carreira",
    "Azul corporativo e verde, direto ao ponto.",
    {
      niche: "Carreira",
      sequence: { first: "bold-hook", middle: ["split"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#0f172a", secondary: "#f8fafc", accent: "#10b981", text: "#0f172a", bg: "#f8fafc" },
        fonts: { heading: "Inter", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
      },
    },
    {
      hook: "Por que você não é chamado para entrevistas",
      title: "Currículo sem resultados",
      body: "Troque tarefas por conquistas mensuráveis. 'Reduzi custos em 18%' pesa muito mais do que 'responsável por compras'.",
      cta: "Envie CV no direct para uma análise",
      photo: "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1080&h=1350",
    },
  ),
  t(
    15,
    "Consultório",
    "Saúde",
    "Verde-água e branco, sério e acessível.",
    {
      niche: "Saúde",
      sequence: { first: "bold-hook", middle: ["numbered", "minimal"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#115e59", secondary: "#f0fdfa", accent: "#14b8a6", text: "#042f2e", bg: "#f7fdfc" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
      },
    },
    {
      hook: "Sinais de que você está desidratado",
      title: "Dor de cabeça no fim da tarde",
      body: "A falta de água reduz o volume de sangue e pode causar dor de cabeça e cansaço. Beba antes de sentir sede.",
      cta: "Compartilhe com alguém que esquece de beber água",
    },
  ),
  t(
    16,
    "Patas",
    "Pets",
    "Laranja alegre e azul, divertido e caloroso.",
    {
      niche: "Pets",
      sequence: { first: "bold-hook", middle: ["numbered"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#c2410c", secondary: "#fff7ed", accent: "#0ea5e9", text: "#1c1917", bg: "#fffbf5" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "dots",
      },
    },
    {
      hook: "Alimentos comuns que são veneno para cães",
      title: "Uva e uva-passa",
      body: "Mesmo em pequena quantidade, podem causar insuficiência renal aguda. Se o cão comer, procure o veterinário na hora.",
      cta: "Salve e mande para outros tutores",
    },
  ),
  t(
    17,
    "Planta Baixa",
    "Arquitetura",
    "Concreto e terracota, editorial minimalista.",
    {
      niche: "Arquitetura e Decoração",
      sequence: { first: "editorial", middle: ["editorial", "split"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#44403c", secondary: "#fafaf9", accent: "#c2410c", text: "#1c1917", bg: "#f4f2ee" },
        fonts: { heading: "Space Grotesk", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "frame",
      },
    },
    {
      hook: "Erros que deixam sua sala menor",
      title: "Tapete pequeno demais",
      body: "O tapete deve passar por baixo pelo menos dos pés da frente do sofá. Peças soltas fragmentam o espaço.",
      cta: "Salve para a sua reforma",
    },
    "business",
  ),
  t(
    18,
    "Mono",
    "Geral",
    "Preto e branco puro. Funciona para qualquer nicho.",
    {
      sequence: { first: "minimal", middle: ["minimal", "numbered"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#0a0a0a", secondary: "#ffffff", accent: "#0a0a0a", text: "#0a0a0a", bg: "#ffffff" },
        fonts: { heading: "Inter", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
      },
    },
    {
      hook: "Menos é mais. Principalmente aqui",
      title: "Uma ideia por slide",
      body: "Cada slide precisa de um único ponto. Se você precisa explicar duas coisas, são dois slides.",
      cta: "Siga para mais dicas de conteúdo",
    },
  ),
  t(
    19,
    "Sunset",
    "Geral",
    "O preto e o gradiente laranja→rosa do slidely.",
    {
      sequence: { first: "bold-hook", middle: ["numbered", "split"], penultimate: "quote", last: "cta-strong" },
      theme: {
        colors: { primary: "#0a0a0a", secondary: "#f5f5f4", accent: "#ff7a1a", text: "#f5f5f4", bg: "#0a0a0a" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "glow",
      },
    },
    {
      hook: "Carrosséis que param o scroll",
      title: "Gancho nos 3 primeiros segundos",
      body: "O primeiro slide decide se o resto será visto. Prometa um resultado ou exponha uma dor específica.",
      cta: "Comente CARROSSEL e receba o guia",
    },
  ),

  // -------------------------------------------------------------------------
  // Coleção Pro
  // -------------------------------------------------------------------------
  pro(
    20,
    "Manchete",
    "Notícias",
    "Editorial de revista: manchete serifada, fios finos e rótulos de seção.",
    {
      niche: "Notícias e atualidades",
      sequence: { first: "magazine", middle: ["magazine"], penultimate: "quote", last: "cta-strong" },
      formats: { list: "checklist", stat: "big-stat", quote: "quote" },
      theme: {
        colors: { primary: "#141414", secondary: "#f4efe6", accent: "#c8102e", text: "#141414", bg: "#f4efe6" },
        fonts: { heading: "Playfair Display", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
        texture: "grain",
        highlight: "underline",
      },
    },
    {
      kicker: "Economia",
      hook: "O que muda no seu **bolso** com a nova regra",
      title: "A regra que ninguém explicou",
      body: "A mudança entra em vigor no próximo mês e afeta quem recebe acima de dois salários. Entenda **o que fazer agora** para não ser pego de surpresa.",
      cta: "Salve e compartilhe com quem precisa saber",
      stat: { value: "36%", label: "dos brasileiros não sabem que serão afetados", body: "Pesquisa com 2 mil entrevistados em 2026." },
      list: { title: "O que fazer **esta semana**", items: ["Confira seu contracheque", "Simule o novo desconto", "Revise seus gastos fixos"] },
    },
  ),
  pro(
    21,
    "Fio",
    "Criadores",
    "Estilo post de X/Threads: avatar, verificado e texto grande. O formato que mais retém.",
    {
      niche: "Criadores de conteúdo",
      sequence: { first: "tweet", middle: ["tweet"], penultimate: "tweet", last: "tweet" },
      formats: { list: "tweet", stat: "tweet", quote: "tweet" },
      theme: {
        colors: { primary: "#0f1419", secondary: "#ffffff", accent: "#1d9bf0", text: "#0f1419", bg: "#ffffff" },
        fonts: { heading: "Inter", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
        highlight: "color",
      },
    },
    {
      hook: "Fiz 100 posts em 100 dias. **Isso é o que aprendi:**",
      title: "1. Consistência vence talento",
      body: "Os posts que mais cresceram não foram os melhores. Foram os que eu publiquei **no dia em que não queria**.",
      cta: "Se isso te ajudou, salva e me segue pra parte 2",
      list: { title: "O que eu faria diferente:", items: ["- Começaria mais cedo", "- Postaria sem medo de errar", "- Responderia todo comentário"] },
    },
  ),
  pro(
    22,
    "Fio Dark",
    "Criadores",
    "O estilo post em modo escuro, com contraste alto.",
    {
      niche: "Criadores de conteúdo",
      sequence: { first: "tweet", middle: ["tweet"], penultimate: "tweet", last: "tweet" },
      formats: { list: "tweet", stat: "tweet", quote: "tweet" },
      theme: {
        colors: { primary: "#16181c", secondary: "#e7e9ea", accent: "#1d9bf0", text: "#e7e9ea", bg: "#000000" },
        fonts: { heading: "Inter", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
        highlight: "color",
      },
    },
    {
      hook: "Ninguém te conta isso sobre **trabalhar sozinho**:",
      title: "A liberdade tem um preço",
      body: "Sem chefe, sem horário e sem ninguém pra cobrar. É aí que a **disciplina** vira o seu maior ativo.",
      cta: "Comenta EU se você também trabalha sozinho",
    },
  ),
  pro(
    23,
    "Suíço",
    "Negócios",
    "Tipografia suíça: grade, números gigantes e vermelho de acento.",
    {
      niche: "Negócios e empreendedorismo",
      sequence: { first: "bold-hook", middle: ["numbered", "split"], penultimate: "quote", last: "cta-strong" },
      formats: { list: "checklist", stat: "big-stat" },
      theme: {
        colors: { primary: "#111111", secondary: "#f2f2f2", accent: "#e63946", text: "#111111", bg: "#f2f2f2" },
        fonts: { heading: "Space Grotesk", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "grid",
        highlight: "color",
      },
    },
    {
      kicker: "Método",
      hook: "3 números que definem se sua empresa **vai sobreviver**",
      title: "Margem de contribuição",
      body: "Quanto sobra de cada venda depois dos custos variáveis. Se ela for **menor que 30%**, crescer vai aumentar o problema.",
      cta: "Salve para revisar no fechamento do mês",
      stat: { value: "82%", label: "das empresas que fecham têm problema de **caixa**, não de venda", body: "Fonte: Sebrae, estudo de sobrevivência de empresas." },
      list: { title: "Revise **todo mês**", items: ["Margem de contribuição", "Ponto de equilíbrio", "Prazo médio de recebimento"] },
    },
  ),
  pro(
    24,
    "Aurora",
    "Tecnologia",
    "Cartões de vidro fosco sobre gradiente em malha. Visual de produto premium.",
    {
      niche: "Tecnologia e produtos digitais",
      sequence: { first: "glass", middle: ["glass"], penultimate: "glass", last: "glass" },
      formats: { list: "glass", stat: "big-stat", quote: "glass" },
      theme: {
        colors: { primary: "#4338ca", secondary: "#eef2ff", accent: "#ec4899", text: "#0b0b1a", bg: "#0b0b1a" },
        fonts: { heading: "Space Grotesk", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
        texture: "grain",
        highlight: "marker",
      },
    },
    {
      kicker: "IA na prática",
      hook: "5 ferramentas de IA que **substituem** um time inteiro",
      title: "Automatize o repetitivo",
      body: "Tudo que você faz mais de três vezes por semana pode virar um fluxo. Comece pelos **relatórios**.",
      cta: "Salve e teste uma por semana",
      list: { title: "Comece por aqui", items: ["Resumos de reunião", "Respostas de e-mail", "Relatórios semanais"] },
    },
    "business",
  ),
  pro(
    25,
    "Neo Brutal",
    "Marketing Digital",
    "Bordas grossas, sombra dura e amarelo vibrante. Impossível de ignorar no feed.",
    {
      niche: "Marketing digital",
      sequence: { first: "brutal", middle: ["brutal"], penultimate: "brutal", last: "brutal" },
      formats: { list: "brutal", stat: "big-stat", quote: "brutal" },
      theme: {
        colors: { primary: "#111111", secondary: "#ffffff", accent: "#ff5c8a", text: "#111111", bg: "#ffd84d" },
        fonts: { heading: "Space Grotesk", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "dots",
        texture: "grain",
        highlight: "marker",
      },
    },
    {
      kicker: "Erro nº 1",
      hook: "Pare de postar **todo dia**. Faça isso no lugar:",
      title: "Qualidade escala, volume cansa",
      body: "Um post que é salvo vale mais que dez que só são vistos. Troque frequência por **profundidade**.",
      cta: "Comente PLANO e receba o calendário",
      list: { title: "Checklist do post salvável", items: ["Gancho com uma promessa clara", "Uma ideia por slide", "CTA pedindo o salvamento"] },
    },
  ),
  pro(
    26,
    "Consultoria",
    "Negócios",
    "Azul corporativo, checklists e dados. Para consultores, B2B e LinkedIn.",
    {
      niche: "Consultoria e B2B",
      sequence: { first: "minimal", middle: ["numbered", "minimal"], penultimate: "quote", last: "cta-strong" },
      formats: { list: "checklist", stat: "big-stat" },
      theme: {
        colors: { primary: "#0b1f3a", secondary: "#ffffff", accent: "#0ea5a4", text: "#0b1f3a", bg: "#ffffff" },
        fonts: { heading: "Inter", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
        highlight: "marker",
      },
    },
    {
      kicker: "Estratégia",
      hook: "Por que **80% dos projetos** atrasam, e como evitar",
      title: "Escopo sem dono",
      body: "Quando todo mundo aprova, ninguém decide. Defina **um responsável** por entrega antes do kickoff.",
      cta: "Envie PROJETO por DM e receba o template",
      stat: { value: "3,2x", label: "mais entregas no prazo com um dono por escopo", body: "Levantamento com 140 projetos entre 2024 e 2026." },
      list: { title: "Antes do **kickoff**", items: ["Um dono por entrega", "Critério de pronto escrito", "Ritual semanal de 15 minutos"] },
    },
  ),
  pro(
    27,
    "Luxo",
    "Premium",
    "Preto e dourado com serifa. Para marcas de alto padrão, joias, imóveis e estética.",
    {
      niche: "Marcas premium",
      sequence: { first: "magazine", middle: ["magazine", "minimal"], penultimate: "quote", last: "cta-strong" },
      formats: { list: "checklist", stat: "big-stat", quote: "quote" },
      theme: {
        colors: { primary: "#0b0b0b", secondary: "#f5efe0", accent: "#c8a45a", text: "#f5efe0", bg: "#0b0b0b" },
        fonts: { heading: "Playfair Display", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "frame",
        texture: "grain",
        highlight: "color",
      },
    },
    {
      kicker: "Coleção",
      hook: "O detalhe que faz uma peça **durar gerações**",
      title: "Acabamento feito à mão",
      body: "Cada peça passa por 40 horas de trabalho artesanal. É o tempo que transforma metal em **herança**.",
      cta: "Agende sua visita pelo direct",
      stat: { value: "40h", label: "de trabalho artesanal em cada peça" },
    },
    "business",
  ),
  pro(
    28,
    "Pastel",
    "Lifestyle",
    "Rosa pastel, checklists leves e marca-texto. Para rotina, beleza e bem-estar.",
    {
      niche: "Lifestyle e bem-estar",
      sequence: { first: "bold-hook", middle: ["checklist", "numbered"], penultimate: "quote", last: "cta-strong" },
      formats: { list: "checklist", stat: "big-stat" },
      theme: {
        colors: { primary: "#f9a8d4", secondary: "#fff1f7", accent: "#db2777", text: "#3b0a24", bg: "#fff1f7" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "dots",
        highlight: "marker",
      },
    },
    {
      kicker: "Rotina",
      hook: "Minha rotina de **manhã** em 20 minutos",
      title: "Água antes do café",
      body: "Um copo grande ao acordar reidrata o corpo depois de 8 horas. Parece bobo, mas **muda o dia**.",
      cta: "Salve para testar amanhã cedo",
      list: { title: "Os 5 passos", items: ["Água ao acordar", "5 minutos de alongamento", "Luz natural na janela", "Café sem celular", "Lista de 3 prioridades"] },
    },
  ),
  pro(
    29,
    "Signature",
    "Geral",
    "A identidade do slidely: preto, laranja e rosa, com dados e listas de alto contraste.",
    {
      sequence: { first: "bold-hook", middle: ["numbered", "minimal"], penultimate: "quote", last: "cta-strong" },
      formats: { list: "checklist", stat: "big-stat" },
      theme: {
        colors: { primary: "#0a0a0a", secondary: "#f5f5f4", accent: "#ff7a1a", text: "#f5f5f4", bg: "#0a0a0a" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "glow",
        texture: "grain",
        highlight: "color",
      },
    },
    {
      kicker: "Guia rápido",
      hook: "Carrosséis que **param o scroll** seguem 3 regras",
      title: "Gancho em 3 segundos",
      body: "O primeiro slide decide se o resto será visto. Prometa **um resultado** ou exponha uma dor específica.",
      cta: "Comente CARROSSEL e receba o guia",
      stat: { value: "3x", label: "mais salvamentos com uma ideia por slide" },
      list: { title: "As **3 regras**", items: ["Gancho com promessa clara", "Uma ideia por slide", "CTA pedindo o salvamento"] },
    },
  ),

  pro(
    30,
    "Capa Real",
    "Finanças",
    "Foto real em tela cheia na capa, marca-texto âmbar e grão de filme.",
    {
      niche: "Finanças pessoais",
      sequence: { first: "photo-cover", middle: ["photo-split", "numbered"], penultimate: "quote", last: "cta-strong" },
      formats: { list: "checklist", stat: "big-stat" },
      theme: {
        colors: { primary: "#0f172a", secondary: "#fafaf9", accent: "#f59e0b", text: "#0f172a", bg: "#fafaf9" },
        fonts: { heading: "Montserrat", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
        highlight: "marker",
        texture: "grain",
      },
    },
    {
      kicker: "Dinheiro",
      hook: "Onde foi parar o seu **salário**?",
      title: "O vazamento invisível",
      body: "Assinaturas esquecidas, taxas do banco e delivery somam **R$ 600 por mês** em média. Ninguém sente, mas o extrato sente.",
      cta: "Salve e faça a faxina no extrato hoje",
      stat: { value: "R$ 600", label: "por mês em gastos que você **não percebe**" },
      list: { title: "Corte primeiro", items: ["Assinaturas sem uso", "Tarifas do banco", "Compras por impulso no app"] },
      photo: "https://images.pexels.com/photos/4386431/pexels-photo-4386431.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1080&h=1350",
      photo2: "https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1080&h=1350",
    },
  ),
  pro(
    31,
    "Documental",
    "Negócios",
    "Fotojornalismo: foto real, manchete serifada e fios editoriais.",
    {
      niche: "Negócios e carreira",
      sequence: { first: "photo-cover", middle: ["magazine", "photo-split"], penultimate: "quote", last: "cta-strong" },
      formats: { list: "checklist", stat: "big-stat", quote: "quote" },
      theme: {
        colors: { primary: "#111111", secondary: "#f5f3ef", accent: "#1d4ed8", text: "#111111", bg: "#f5f3ef" },
        fonts: { heading: "Playfair Display", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
        highlight: "underline",
        texture: "grain",
      },
    },
    {
      kicker: "Bastidores",
      hook: "A reunião que mudou **a empresa**",
      title: "Menos slides, mais decisões",
      body: "Trocamos a apresentação semanal por um documento de uma página. As reuniões caíram de uma hora para **vinte minutos**.",
      cta: "Siga para mais bastidores de gestão",
      stat: { value: "-67%", label: "de tempo em reunião depois da mudança" },
      photo: "https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1080&h=1350",
      photo2: "https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1080&h=1350",
    },
  ),
  pro(
    32,
    "Studio",
    "Tecnologia",
    "Foto escura de estúdio, ciano elétrico e tipografia técnica.",
    {
      niche: "Tecnologia e programação",
      sequence: { first: "photo-cover", middle: ["photo-split", "numbered"], penultimate: "quote", last: "cta-strong" },
      formats: { list: "checklist", stat: "big-stat" },
      theme: {
        colors: { primary: "#0a0a0a", secondary: "#e5f9fc", accent: "#22d3ee", text: "#f1f5f9", bg: "#0a0a0a" },
        fonts: { heading: "Space Grotesk", body: "Inter" },
        handle: "",
        logoUrl: null,
        decoration: "none",
        highlight: "color",
        texture: "grain",
      },
    },
    {
      kicker: "Dev",
      hook: "O hábito que separa **júnior de sênior**",
      title: "Ler código antes de escrever",
      body: "Sêniores passam mais tempo lendo o código existente do que escrevendo. Entender o sistema evita **metade dos bugs**.",
      cta: "Comente CÓDIGO e receba o roteiro de estudos",
      list: { title: "Rotina de leitura", items: ["Leia o PR de um colega por dia", "Rastreie um fluxo do início ao fim", "Anote o que não entendeu"] },
      photo: "https://images.pexels.com/photos/5926382/pexels-photo-5926382.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1080&h=1350",
      photo2: "https://images.pexels.com/photos/4050315/pexels-photo-4050315.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1080&h=1350",
    },
  ),
];

export const TEMPLATE_BY_ID = new Map(TEMPLATE_CATALOG.map((template) => [template.id, template]));
